<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>phone_number</name>
   <tag></tag>
   <elementGuidId>2acc26d4-ff86-4364-b3d9-0fc6ab85511e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fr3556-field' and @name = 'phoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fr3556-field</value>
      <webElementGuid>d2664f1f-42ab-408d-8400-3e813c2bab78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>95038c48-502a-44b7-adf5-c50167e7fea6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
