<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>relationship_type</name>
   <tag></tag>
   <elementGuidId>54d89470-e20f-4bf1-8052-9bc7238de6d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'relationship_type' and @name = 'relationship_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>relationship_type</value>
      <webElementGuid>59e6d31f-f191-48fa-b2fe-3e829f561c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>relationship_type</value>
      <webElementGuid>9297c002-c613-4dd6-b7c6-6eefdb69a292</webElementGuid>
   </webElementProperties>
</WebElementEntity>
