<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>relationship_type</name>
   <tag></tag>
   <elementGuidId>54d89470-e20f-4bf1-8052-9bc7238de6d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-val = 'Sibling']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>relationship_type</value>
      <webElementGuid>980525bb-42ad-481a-820c-b1bbe5e392ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>relationship_type</value>
      <webElementGuid>7ad2dba1-f09c-4689-9794-c29783e878ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>Sibling</value>
      <webElementGuid>4778ee76-3549-4942-903c-10393f4f7a10</webElementGuid>
   </webElementProperties>
</WebElementEntity>
